# This is the full content for your ekf.yaml file.
# Replace the entire file with this.

/**:
  ros__parameters:
    # GENERAL SETTINGS
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: true
    publish_tf: true

    # FRAME PARAMETERS - Corrected from our debugging
    
    odom_frame: robot_odom
    base_link_frame: robot_base_footprint
    world_frame: robot_odom

    # ODOMETRY SENSOR (odom0)
    odom0: /atlas/robotnik_base_controller/odometry
    odom0_config:
      [false, false, false,  # X, Y, Z
       false, false, false,  # Roll, Pitch, Yaw
       true,  false,  false,  # Vx, Vy, Vz
       false, false, true,   # Vroll, Vpitch, Vyaw
       false, false, false]  # Ax, Ay, Az

    # --- IMU SENSOR (imu0) ---
    # The IMU is intentionally left out because its covariance is zero.

    # --- INITIAL STATE AND PROCESS NOISE ---

    print_diagnostics: true             # Enable diagnostic output
    debug: true                      # Set to true for verbose debugging
    debug_out_file: /tmp/debug_ekf_localization.txt