/**:
  ros__parameters:
    robot_base_frame: robot_base_footprint
    odom_frame: robot_odom
    global_frame: robot_map
    costmap_topic: "local_costmap/costmap_raw"   # use local costmap for recoveries
    footprint_topic: "local_costmap/published_footprint"
    cycle_frequency: 10.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    progress_checker:
      plugin: "nav2_behavior_tree::ProgressChecker"
    general_goal_checker:
      plugin: "nav2_controller::ScaledOrientationGoalChecker"