/**:
  ros__parameters:
    global_frame: robot_map
    robot_base_frame: robot_base_footprint
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    track_unknown_space: true
    map_topic: "/atlas/map"
    subscribe_to_updates: false
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: front_laser rear_laser
      front_laser:
        topic: "/atlas/front_lidar/scan"
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: "LaserScan"
      rear_laser:
        topic: "/atlas/rear_lidar/scan"
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: "LaserScan"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6
      cost_scaling_factor: 3.0