/**:
  ros__parameters:
    robot_base_frame: robot_base_footprint
    odom_frame: robot_odom
    global_frame: robot_map
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.5
      downsample_costmap: false
      allow_replanning: true