/**:
  ros__parameters:
    robot_base_frame: robot_base_footprint
    odom_frame: robot_odom
    global_frame: robot_map
    smoother_plugins: ["Simple"]
    Simple:
      plugin: "nav2_smoother::SimpleSmoother"